version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deposit-system
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - deposit-system

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - deposit-system
    command: ["redis-server", "--appendonly", "yes"]

  reading-system:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: deposit-system
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deposit-system
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      JWT_SECRET: MY_SECRET
    depends_on:
      - postgres
    restart: always
    networks:
      - deposit-system

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  deposit-system:
    name: deposit-system
    driver: bridge
